#ifndef REPLY_HPP
#define REPLY_HPP
#include <string>
#include <User.hpp>

enum Reply
{
	
	RPL_WELCOME = 1,
	RPL_YOURHOST = 2,
	RPL_CREATED = 3,
	RPL_MYINFO = 4,
	RPL_BOUNCE = 5,
	RPL_TOPIC = 332,
	RPL_AWAY = 301,
	RPL_WHOREPLY = 352,
	RPL_ENDOFWHO = 315,
	ERR_NOSUCHNICK = 401,
	ERR_NEEDMOREPARAMS = 461,
	ERR_BANNEDFROMCHAN = 474,
	ERR_INVITEONLYCHAN = 473,
	ERR_BADCHANNELKEY = 475,
	ERR_CHANNELISFULL = 471,
	ERR_BADCHANMASK = 476,
	ERR_TOOMANYCHANNELS = 405,
	ERR_NOSUCHCHANNEL = 403,
	ERR_CHANOPRIVSNEEDED = 482,
	ERR_USERNOTINCHANNEL = 441,
	ERR_NOTONCHANNEL = 442,
	ERR_NONICKNAMEGIVEN = 431,
	ERR_ERRONEUSNICKNAME = 432,
	ERR_NICKNAMEINUSE = 433,
	ERR_NICKCOLLISION = 436,
	ERR_UNAVAILRESOURCE = 437,
	ERR_RESTRICTED = 484,
	ERR_ALREADYREGISTRED = 462,
	ERR_NOORIGIN = 409,
	ERR_NOSUCHSERVER = 402,
	ERR_NORECIPIENT = 411,
	ERR_NOTEXTTOSEND = 412,
	ERR_CANNOTSENDTOCHAN = 404,
	ERR_NOTOPLEVEL = 413,
	ERR_WILDTOPLEVEL = 414,
	ERR_TOOMANYTARGETS = 407,

};

typedef enum Reply Reply;

const std::string generateReply(Reply reply, const User &target, const std::string &content);
#endif